I replaced 3 config_ (source, target, exclusion) files by config_doBackup file. Minor corrections.

diff --git a/doBackup b/doBackup
--- a/doBackup
+++ b/doBackup
@@ -16,29 +16,50 @@
 #             list of the content of backup files.
 #             There is a exclusion file where you can establish all you will 
 #             not want to copy. 
-# Requires  : file_source #The file where configure the source backup folder
-#             file_target #The file where configure the Target backup folder
-#             file_exclusion #The file where configure the path and filename of 
-#             exclusion file
-# Files     : The full backup name is        'year-month-0-hostname-full.tar.bz2'
-#             The incremental backup name is 'year-month-day-hostname-inc.tar.bz2'
-#             The logs files has the same name but ending with .log instead of 
-#             .tar.gz2
-#             There is a .snap file that maintains the list of files to be 
+# Requires  : 'config_doBackup' is a text file with 2 or 3 lines
+#             Fist line must contain the 'source backup folder'. Example: /home/user
+#             Second line must contain the 'target backup folder'. Example: /smb/bck/user
+#             Third line can contain the 'exclusion file' or nothing (is optional).
+# Files out : The monthly full backup name is 'year-month-0-hostname-full.tar.bz2'
+#             The monthly full backup log is  'year-month-0-hostname.log'
+#             The incremental backup name is  'year-month-day-hostname-inc.tar.bz2'
+#             The incremental backup log is   'year-month-day-hostname.log'
+#             There is a monthly .snap file that maintains the list of files to be 
 #             copied to the incremental backups
 # Automation: To automate the backup, run this script from /etc/rc.local (as 
 #             root) or ~/.bashrc (as user) to make the backup when the computer 
-#             is power on
+#             is power on. Or put in the crontab
 # Usage     : ./doBackup &
 ##############################################################################
 
-#CONFIGURATION CONSTANTS - CHANGE THE VALUES IN THE CONFIGURATION FILES
-read -r v_backup_source  < "config_source"    || echo "ERROR: 'config_source' file not exist"; exit 1     #Source backup folder
-read -r v_backup_target  < "config_target"    || echo "ERROR: 'config_target' file not exist"; exit 1     #Target backup folder
-read -r v_exclusion_file < "config_exclusion" || echo "ERROR: 'config_exclusion' file not exist"; exit 1  #PATH and filename of exclusion file
+##############################################################################
+#
+# Check config file. The config_doBackup is a text file with 2 or 3 lines
+#    Fist line must contain the 'source backup folder'. Example: /home/user
+#    Second line must contain the 'target backup folder'. Example: /smb/bck/user
+#    Third line can contain the 'exclusion file' or nothing. 
+#
+##############################################################################
+   if [[ -f config_doBackup ]]
+   then
+      {
+          read -r v_backup_source    #Source backup folder
+          read -r v_backup_target    #Target backup folder
+          read -r v_exclusion_file   #PATH and filename of exclusion file
+      } < config_doBackup            #Config file whit 2 or 3 lines: Source backup folder, Target backup folder, PATH and filename of exclusion file (optional)
+   else
+      echo "ERROR: Does not exist the config file: config_doBackup"
+      exit 1
+   fi
+   [[ -n "$v_backup_source" ]] || { echo "ERROR in config_doBackup: Fist line must contain the 'source backup folder'. Example: /home/user" >&2; exit 1; }
+   [[ -n "$v_backup_target" ]] || { echo "ERROR in config_doBackup: Second line must contain the 'target backup folder'. Example: /smb/bck/user" >&2; exit 1; }
 
-#Variables
-         V_VERSION="20151113"        #Version of this script 
+##############################################################################
+#
+# Variables
+#
+##############################################################################
+         V_VERSION="20151114"        #Version of this script 
         v_hostname=$(/bin/uname -n)  #Hostname where the script runs
       v_today_year=$(date +%Y)       #Year of today's date 
      v_today_month=$(date +%m)       #Month of today's date
@@ -53,6 +74,16 @@ read -r v_exclusion_file < "config_exclusion" || echo "ERROR: 'config_exclusion'
 
 ##############################################################################
 #
+# Create the timestamp
+#
+##############################################################################
+f_timestamp ()
+{
+   v_timestamp=$(date +%Y%m%d_%H%M%S)
+}
+
+##############################################################################
+#
 # Annotate the timestamp and the message in the log file
 #
 ##############################################################################
@@ -64,16 +95,6 @@ f_log ()
 
 ##############################################################################
 #
-# Create the timestamp
-#
-##############################################################################
-f_timestamp ()
-{
-   v_timestamp=$(date +%Y%m%d_%H%M%S)
-}
-
-##############################################################################
-#
 # Check if there is source directory of the backup
 # No  --> exit
 # yes --> cd
@@ -81,7 +102,8 @@ f_timestamp ()
 ##############################################################################
 f_source_exist ()
 {
-   if [ ! -d $v_backup_source ]; then
+   if [[ ! -d "$v_backup_source" ]]
+   then
       f_log "ERROR: Does not exist the source directory of the backup: $v_backup_source . Process aborted"
       exit 1
    else
@@ -98,9 +120,10 @@ f_source_exist ()
 ##############################################################################
 f_target_exist ()
 {
-   if [ ! -d $v_backup_target ]; then
+   if [[ ! -d "$v_backup_target" ]]
+   then
       mkdir -p $v_backup_target
-      if [ "$?" -ne 0 ]
+      if [[ "$?" -ne 0 ]]
       then
          f_log "ERROR: Can't create target directory of the backup: $v_backup_target . Process aborted"
          exit 1
@@ -117,7 +140,7 @@ f_target_exist ()
 ##############################################################################
 f_exclusion_exist ()
 {
-   if [ ! -f $v_exclusion_file ]; 
+   if [[ ! -f "$v_exclusion_file" ]]
    then
       f_log "ERROR: Does not exist the exclusion file: $v_exclusion_file"
       v_exclusions=1
@@ -135,11 +158,11 @@ f_exclusion_exist ()
 ##############################################################################
 f_full_inc ()
 {
-   if [ ! -f $v_backup_full ]
+   if [[ ! -f "$v_backup_full" ]]
    then
       v_backup_file=$v_backup_full
       v_log_file=$v_log_full
-   elif [ ! -f $v_backup_inc ]
+   elif [[ ! -f "$v_backup_inc" ]]
    then
       v_backup_file=$v_backup_inc
       v_log_file=$v_log_inc
